title: The Millennium
author: Sunday Olaoye
email: olaoyesunday@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
 This is to talk about the second advent, the Millennium reign of Christ.

# social links
twitter_username: twitter.com/olaoyesunday
github_username:  https://github.com/olaoyesunday

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
